routes/web.php
<?php
use App\Sessions\Online;

Route::get('/', function () {

    $c = \App\Candidate::find(6);
    return $c->load('review');
    // return view('welcome');
    // return \App\User::all();
    // return unserialize(base64_decode(\App\Sessions\Online::first()->payload));

    // $model = Online::all();
    // $model->map(function ($item, $key) {
    //   $item->payload = collect(
    //       unserialize(base64_decode($item->payload))
    //     );
    //
    //   $item->last_activity = \Carbon\Carbon::createFromTimestamp($item->last_activity)->toDateTimeString();
    // });
    // return $model->all();

    return redirect()->route('dashboard');
});


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function()
{

  Route::get('/', 'DashboardController@index')->name('dashboard');


  Route::get('orders/request', 'OrderRequestController@index')->name('orders.request');
  Route::delete('orders/request/{id}/delete', 'OrderRequestController@destroy')->name('orders.request.destroy');
  Route::post('orders/assign', 'OrderRequestController@assign')->name('orders.assign');
  Route::get('orders/candidate/find', 'OrderRequestController@search')->name('orders.candidate.find');

  Route::resources([
    'services' => 'ServiceController',
    'candidates' => 'CandidateController',
    'orders' => 'OrderController',
    'customers' => 'CustomerController',
  ]);
  Route::put('/candidates/{candidate}/hide', 'CandidateController@hide')->name('candidates.hide');


  Route::get('/feedback', 'FeedbackController@index')->name('feedback.index');
  // Route::get('/feedback/{feedback}/hide', 'FeedbackController@hide')->name('feedback.hide');

  Route::get('/complain', 'ComplainController@index')->name('complain.index');
  // Route::put('/complain/{complain}/hide', 'ComplainController@hide')->name('complain.hide');
  //
  // Route::put('/feedback/{feedback}/hide', 'CandidateController@hide')->name('feedback.hide');
  // Route::put('/feedback/{feedback}/hide', 'CandidateController@hide')->name('feedback.hide');
  //
  // Route::put('/complain/{complain}/hide', 'CandidateController@hide')->name('complain.hide');
  // Route::put('/complain/{complain}/hide', 'CandidateController@hide')->name('complain.hide');

  Route::get('/admin/log/{user}', 'DashboardController@userLog')->name('log');





  Route::get('/chat', function ()
  {
    return view('admin.chat');
  })->name('chat');
  Route::get('/table', function ()
  {
    return view('admin.table');
  })->name('table');

});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $table = 'info_category';

    protected $fillable = [ 'name','photo','photo_hi'];

    public $timestamps = false;


    public function candidates()
    {
      return $this->hasMany('App\Candidate', 'category_id');
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Service;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ServiceController extends Controller
{
    public function __construct(Service $service)
    {
      $this->service = $service;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.services.index')->with('services', $this->service->all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validator($request->all())->validate();

      if ($request->hasFile('photo')) {
        $photo = $request->file('photo');
        $photo_name = 'ic_'. str_slug($request->name) . '.' . $photo->getClientOriginalExtension();
        $folder = public_path('JIBU/assets/categories/');

        if (file_exists($folder.$photo_name)) unlink($folder.$photo_name);

        $photo->move($folder, $photo_name);
      }
      if ($request->hasFile('photo_hi')) {
        $photo_hi = $request->file('photo_hi');
        $photo_hi_name = 'hi_'. str_slug($request->name) . '.' . $photo_hi->getClientOriginalExtension();
        $folder = public_path('JIBU/assets/categories/');

        if (file_exists($folder.$photo_hi_name)) unlink($folder.$photo_hi_name);

        $photo_hi->move($folder, $photo_hi_name);
      }

      $service = $this->service->create([
        'name' => $request->name,
        'photo' => $photo_name ?? 'no_icon.png',
        'photo_hi' => $photo_hi_name ?? 'no_image.jpg'
      ]);

      return ($service) ?
                redirect()->back()->with('success', 'successfully created')
                : redirect()->back()->with('error', 'something wrong');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(Service $service)
    {
      $candidates = $service->candidates()->paginate(10);

      return view('admin.services.show', compact('service', 'candidates'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit(Service $service)
    {
        return view('admin.services.edit', compact('service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Service $service)
    {
      $this->validator($request->all())->validate();

      if ($request->hasFile('photo')) {
        $photo = $request->file('photo');
        $photo_name = 'ic_'. str_slug($request->name) . '.' . $photo->getClientOriginalExtension();
        $folder = public_path('JIBU/assets/categories/');

        if (file_exists($folder.$service->photo ?? 'abc.jpg')) unlink($folder.$service->photo ?? 'abc.jpg');
        if (file_exists($folder.$photo_name)) unlink($folder.$photo_name);

        $photo->move($folder, $photo_name);
        $service->photo = $photo_name;
      }
      if ($request->hasFile('photo_hi')) {
        $photo_hi = $request->file('photo_hi');
        $photo_hi_name = 'hi_'. str_slug($request->name) . '.' . $photo_hi->getClientOriginalExtension();
        $folder = public_path('JIBU/assets/categories/');

        if (file_exists($folder.$service->photo_hi ?? 'abc.jpg')) unlink($folder.$service->photo_hi ?? 'abc.jpg');
        if (file_exists($folder.$photo_hi_name)) unlink($folder.$photo_hi_name);

        $photo_hi->move($folder, $photo_hi_name);
        $service->photo_hi = $photo_hi_name;
      }

      $service->name = $request->name;

      return $service->save() ?
                            redirect()->back()->with('success', 'successfully updated')
                            : redirect()->back()->with('error', 'something wrong');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(Service $service)
    {
      if ($category->image) {
        $folder =  public_path('images/');
        if (file_exists($folder.$category->image)) unlink($folder.$category->image);
      }

      $category_id = Category::where('id', '!=', $category->id)->first()->id;

      $category->allItems->each(function ($item) use ($category_id){
          $item->update(['category_id' => $category_id ]);
      });

      return ($category->delete()) ?
                redirect()->route('admin.categories.index')->with('success', 'successfully Updated')
                : redirect()->route('admin.categories.index')->with('error', 'something wrong');
    }
    protected function validator(array $data)
    {
      $rules = [
        'name' => 'required',
        'photo' => 'nullable|mimetypes:image/png',
        'photo_hi' => 'nullable|mimetypes:image/jpeg,image/jpg',
      ];
      return Validator::make($data, $rules,[
        'photo.mimetypes' => 'Icon Must be .png type',
        'photo_hi.mimetypes' => 'Big Photo Must be .jpg or .jpeg type'
      ]);
    }
}

resources/views/admin/services/create.blade.php
@extends('layouts.back')

@section('content')
  <div class="animated fadeIn" >
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            Create New <strong>Service</strong>
          </div>
          <div class="card-body">
            @if (session('success'))
              <div class="alert alert-info">
                {{session('success')}}
              </div>
            @elseif (session('error'))
              <div class="alert alert-warning">
                {{session('error')}}
              </div>
            @endif
            <form action="{{route('services.store')}}" method="post" enctype="multipart/form-data">
              @csrf
              <div class="form-group">
                <label for="name">Service Name</label>
                <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" type="text" name="name" value="{{ old('name') }}" placeholder="Enter Service Name..">
                @if ($errors->has('name'))
                  <span class="invalid-feedback help-block" role="alert">
                      <strong>{{ $errors->first('name') }}</strong>
                  </span>
                @endif
              </div>
              <div class="form-group">
                <label for="nf-password">Icon</label>
                <input class="form-control-file {{ $errors->has('photo') ? ' is-invalid' : '' }}" type="file" name="photo">
                @if ($errors->has('photo'))
                  <span class="invalid-feedback help-block" role="alert">
                      <strong>{{ $errors->first('photo') }}</strong>
                  </span>
                @endif
              </div>
              <div class="form-group">
                <label for="nf-password">Big Photo</label>
                <input class="form-control-file{{ $errors->has('photo_hi') ? ' is-invalid' : '' }}" type="file" name="photo_hi">
                @if ($errors->has('photo_hi'))
                  <span class="invalid-feedback help-block" role="alert">
                      <strong>{{ $errors->first('photo_hi') }}</strong>
                  </span>
                @endif
              </div>

          </div>
          <div class="card-footer">
            <button class="btn btn-sm btn-primary" type="submit">
              <i class="fa fa-dot-circle-o"></i> Submit</button>
            <button class="btn btn-sm btn-danger" type="reset">
              <i class="fa fa-ban"></i> Reset</button>
              </form>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row-->
  </div>
@endsection

resources/views/admin/services/edit.blade.php
@extends('layouts.back')

@section('content')
  <div class="animated fadeIn" >
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            Edit <strong>{{$service->name}}</strong>
          </div>
          <div class="card-body">
            @if (session('success'))
              <div class="alert alert-info">
                {{session('success')}}
              </div>
            @elseif (session('error'))
              <div class="alert alert-warning">
                {{session('error')}}
              </div>
            @endif
            <form action="{{route('services.update', ['id' => $service->id])}}" method="post" enctype="multipart/form-data">
              <input type="hidden" name="_method" value="put">
              @csrf
              <div class="form-group">
                <label for="name">Service Name</label>
                <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" type="text" name="name" value="{{ $service->name }}" placeholder="Enter Service Name..">
                @if ($errors->has('name'))
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $errors->first('name') }}</strong>
                  </span>
                @endif
              </div>
              <div class="form-group">
                <label for="nf-password">Icon</label>
                <img src="{{url('/')}}/JIBU/assets/categories/{{$service->photo}}" width="30px" alt="">
                <input class="form-control{{ $errors->has('photo') ? ' is-invalid' : '' }}" type="file" name="photo">
                @if ($errors->has('photo'))
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $errors->first('photo') }}</strong>
                  </span>
                @endif
              </div>
              <div class="form-group">
                <label for="nf-password">Big Photo</label>
                <img src="{{url('/')}}/JIBU/assets/categories/{{$service->photo_hi}}" width="60px" alt="">
                <input class="form-control{{ $errors->has('photo_hi') ? ' is-invalid' : '' }}" type="file" name="photo_hi">
                @if ($errors->has('photo_hi'))
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $errors->first('photo_hi') }}</strong>
                  </span>
                @endif
              </div>

          </div>
          <div class="card-footer">
            <button class="btn btn-sm btn-primary" type="submit">
              <i class="fa fa-dot-circle-o"></i> Submit</button>
            <button class="btn btn-sm btn-danger" type="reset">
              <i class="fa fa-ban"></i> Reset</button>
              </form>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row-->
  </div>
@endsection

resources/views/admin/services/index.blade.php
@extends('layouts.back')

@section('content')
  <div class="animated fadeIn" >
    <div class="row">
      <div class="col-sm-6 col-md-3">
        <div class="card">
          <div class="card-body  text-secondary text-center">
            <div class="h1 mb-4">
              <i class="icon-plus"></i>
            </div>
            <div class="text-value">
              <a href="{{route('services.create')}}" class="text-secondary">
                Add Service
              </a>
            </div>
          </div>
        </div>
      </div>
        @php
          $color = [
            'info',
            'warning',
            'success',
            'danger',
            'primary'
          ];
          $i=0;
        @endphp

        @foreach ($services as $service)
          <div class="col-sm-6 col-md-3">
            <div class="card">
              <div class="card-body text-{{$color[$i]}} text-center">
                <div class="h1 mb-4" >
                  {{-- <i class="icon-user-follow"></i> --}}
                  <img src="{{url('/')}}/JIBU/assets/categories/{{$service->photo}}" alt="">
                </div>
                <div class="text-value">
                  <a href="{{route('services.show', ['id' => $service->id])}}" class="text-{{$color[$i]}}">
                    {{$service->name}}
                  </a>
                </div>
              </div>
            </div>
          </div>
        @php
        $i++;
         if (empty($color[$i])) {
           $i = 0;
         }
        @endphp
        @endforeach
        <!-- /.col-->
      </div>
    <!-- /.row-->
  </div>
@endsection

resources/views/admin/services/show.blade.php
@extends('layouts.back')

@section('content')
  <div class="animated fadeIn" style="box-shadow: 0 0 15px #cfcfcf">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header text-danger">
            <img src="{{url('/')}}/JIBU/assets/categories/{{$service->photo}}" alt="{{$service->name}}" width="30px">
            <strong>{{$service->name}}</strong>'s info
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-4">
                <div class="card">
                  <img class="card-img-top" src="{{url('/')}}/JIBU/assets/categories/{{$service->photo_hi}}" alt="{{$service->name}}" width="100%">
                </div>
              </div>
              <div class="col-md-8">
                <h3>{{$service->name}}</h3>
                <hr>
                <div>
                  <strong>total candidates: </strong>{{count($candidates)}}
                </div>
                <hr>
                <div>
                  <a class="btn btn-sm btn-warning" href="{{route('services.edit', ['id' => $service->id])}}">
                    <i class="fa fa-edit"></i> Edit
                  </a>

                  <a class="btn btn-sm btn-danger" data-toggle="modal" data-target="#serviceDelete"
                      href="{{route('services.edit', ['id' => $service->id])}}">
                    <i class="fa fa-trash"></i> Delete
                  </a>
                  <a class="btn btn-sm btn-secondary" data-toggle="modal" data-target="#serviceDelete"
                      href="{{route('services.edit', ['id' => $service->id])}}">
                    <i class="fa fa-eye-slash"></i> Hide
                  </a>
                </div>
              </div>
              <div class="col-md-12">
                <div class="card">
                  <div class="card-header">
                    <i class="fa fa-align-justify"></i> Candidates</div>
                  <div class="card-body">
                    <table class="table table-responsive-sm table-hover">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Mobile</th>
                          <th>Address</th>
                          <th>Gender</th>
                          <th>Badge</th>
                          <th>Status</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        @forelse ($candidates as $candidate)
                          <tr>
                            <td>{{$candidate->name}}</td>
                            <td>{{$candidate->office->phone}}</td>
                            <td>{{$candidate->address}}</td>
                            <td>{{$candidate->gender}}</td>
                            <td>{{$candidate->level->level_name}}</td>
                            <td>
                              <span class="badge badge-{{$candidate->status ? 'success': 'danger'}}">{{$candidate->status ? 'Active' : 'Inactive'}}</span>
                            </td>
                            <td>
                              <a title="Show Canidate" class="btn btn-sm btn-info" href="{{route('candidates.show', ['id' => $candidate->id])}}">
                                <i class="fa fa-eye"></i>
                              </a>
                              <a title="Edit Canidate" class="btn btn-sm btn-warning" href="{{route('candidates.edit', ['id' => $candidate->id])}}">
                                <i class="fa fa-edit"></i>
                              </a>
                              <a title="Delete Canidate" class="btn btn-sm btn-danger" href="{{route('candidates.show', ['id' => $candidate->id])}}">
                                <i class="fa fa-trash"></i>
                              </a>
                            </td>
                          </tr>
                        @empty

                        @endforelse
                      </tbody>
                    </table>
                    {{$candidates->render()}}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.col-->
    </div>
    <!-- /.row-->
  </div>


  <div class="modal fade" id="serviceDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-danger" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Are You Sure?</h4>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          <p>It will be effected to related field. (Candidate)</p>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
          <button class="btn btn-danger" type="button">Delete</button>
        </div>
      </div>
      <!-- /.modal-content-->
    </div>
    <!-- /.modal-dialog-->
  </div>

@endsection