routes/web.php
<?php
use App\Sessions\Online;

Route::get('/', function () {

    $c = \App\Candidate::find(6);
    return $c->load('review');
    // return view('welcome');
    // return \App\User::all();
    // return unserialize(base64_decode(\App\Sessions\Online::first()->payload));

    // $model = Online::all();
    // $model->map(function ($item, $key) {
    //   $item->payload = collect(
    //       unserialize(base64_decode($item->payload))
    //     );
    //
    //   $item->last_activity = \Carbon\Carbon::createFromTimestamp($item->last_activity)->toDateTimeString();
    // });
    // return $model->all();

    return redirect()->route('dashboard');
});


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function()
{

  Route::get('/', 'DashboardController@index')->name('dashboard');


  Route::get('orders/request', 'OrderRequestController@index')->name('orders.request');
  Route::delete('orders/request/{id}/delete', 'OrderRequestController@destroy')->name('orders.request.destroy');
  Route::post('orders/assign', 'OrderRequestController@assign')->name('orders.assign');
  Route::get('orders/candidate/find', 'OrderRequestController@search')->name('orders.candidate.find');

  Route::resources([
    'services' => 'ServiceController',
    'candidates' => 'CandidateController',
    'orders' => 'OrderController',
    'customers' => 'CustomerController',
  ]);
  Route::put('/candidates/{candidate}/hide', 'CandidateController@hide')->name('candidates.hide');


  Route::get('/feedback', 'FeedbackController@index')->name('feedback.index');
  // Route::get('/feedback/{feedback}/hide', 'FeedbackController@hide')->name('feedback.hide');

  Route::get('/complain', 'ComplainController@index')->name('complain.index');
  // Route::put('/complain/{complain}/hide', 'ComplainController@hide')->name('complain.hide');
  //
  // Route::put('/feedback/{feedback}/hide', 'CandidateController@hide')->name('feedback.hide');
  // Route::put('/feedback/{feedback}/hide', 'CandidateController@hide')->name('feedback.hide');
  //
  // Route::put('/complain/{complain}/hide', 'CandidateController@hide')->name('complain.hide');
  // Route::put('/complain/{complain}/hide', 'CandidateController@hide')->name('complain.hide');

  Route::get('/admin/log/{user}', 'DashboardController@userLog')->name('log');





  Route::get('/chat', function ()
  {
    return view('admin.chat');
  })->name('chat');
  Route::get('/table', function ()
  {
    return view('admin.table');
  })->name('table');

});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $table = 'order';

    public $timestamps = false;

    protected $fillable = [
        'order_number',
        'customer_id',
        'candidate_id',
        'book_id',
        'duration',
        'amount',
        'phone',
        'location',
        'start_time',
        'end_time',
        'status',
        'from_request',
        'order_time',
        'confirm_time',
        'finish_time',
    ];

    public function book()
    {
        return $this->belongsTo(BookStructure::class, 'book_id');
    }
    public function candidate()
    {
        return $this->belongsTo(Candidate::class, 'candidate_id');
    }
    public function customer()
    {
        return $this->belongsTo(Customer::class, 'customer_id');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use Illuminate\Http\Request;
use Illuminate\View\View;

class OrderController extends Controller
{
    public function __construct(Order $order)
    {
        $this->order = $order;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(): View
    {
        $orders = $this->order->orderBy('id', 'desc')->paginate(15);
        return view('admin.orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
    }
}

resources/views/admin/orders/create.blade.php
@extends('layouts.back')

@section('content')
  <div class="animated fadeIn" >
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            Add New <strong>Candidate</strong>
          </div>
          <div class="card-body">
            @if (session('success'))
              <div class="alert alert-info">
                {{session('success')}}
              </div>
            @elseif (session('error'))
              <div class="alert alert-warning">
                {{session('error')}}
              </div>
            @endif
            <form action="{{route('candidates.store')}}" method="post" enctype="multipart/form-data">
              @csrf
              <div class="row">
                <div class="col-md-6">
                  <div class="card-body"  style="background: #fafafa; padding:1rem">
                    <div class="form-group">
                      <label class="font-weight-bold">Candidate Name</label>
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" type="text" name="name" value="{{ old('name') }}" placeholder="Enter Candidate Name..">
                      @if ($errors->has('name'))
                        <span class="invalid-feedback help-block" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                      @endif
                    </div>
                    <div class="form-group">
                      <label class="font-weight-bold">Candidate Address</label>
                      <input class="form-control{{ $errors->has('address') ? ' is-invalid' : '' }}" id="address" type="text" name="address" value="{{ old('address') }}" placeholder="Enter Candidate Address..">
                      @if ($errors->has('address'))
                        <span class="invalid-feedback help-block" role="alert">
                            <strong>{{ $errors->first('address') }}</strong>
                        </span>
                      @endif
                    </div>
                    <div class="form-group">
                      <label class="font-weight-bold">Select Gender</label>
                      <div class="form-check">
                        <input class="form-check-input" type="radio" name="gender" value="male" checked>
                        <label class="form-check-label" for="inlineCheckbox2">Male</label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="radio" name="gender" value="female">
                        <label class="form-check-label" for="inlineCheckbox3">Female</label>
                      </div>
                      @if ($errors->has('gender'))
                        <span class="invalid-feedback help-block" role="alert">
                            <strong>{{ $errors->first('gender') }}</strong>
                        </span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="card-body"  style="background: #fafafa; padding:1rem">
                    <div class="form-group">
                      <label class="font-weight-bold">Nationality</label>
                      <input class="form-control{{ $errors->has('nationality') ? ' is-invalid' : '' }}" id="nationality" type="text" name="nationality" value="{{ old('nationality') }}" placeholder="Enter Candidate Nationality..">
                      @if ($errors->has('nationality'))
                        <span class="invalid-feedback help-block" role="alert">
                            <strong>{{ $errors->first('nationality') }}</strong>
                        </span>
                      @endif
                    </div>
                    <div class="form-group">
                      <label class="font-weight-bold">Education Level</label>
                      <input class="form-control{{ $errors->has('education_level') ? ' is-invalid' : '' }}" id="education_level" type="text" name="education_level" value="{{ old('education_level') }}" placeholder="Enter Candidate Education..">
                      @if ($errors->has('education_level'))
                        <span class="invalid-feedback help-block" role="alert">
                            <strong>{{ $errors->first('education_level') }}</strong>
                        </span>
                      @endif
                    </div>
                    <div class="form-group">
                      <label class="font-weight-bold">Religion</label>
                      <input class="form-control{{ $errors->has('religion') ? ' is-invalid' : '' }}" id="religion" type="text" name="religion" value="{{ old('religion') }}" placeholder="Enter Candidate Religion..">
                      @if ($errors->has('religion'))
                        <span class="invalid-feedback help-block" role="alert">
                            <strong>{{ $errors->first('religion') }}</strong>
                        </span>
                      @endif
                    </div>
                    <div class="form-group">
                      <label class="font-weight-bold">Language</label>
                      <input class="form-control{{ $errors->has('language') ? ' is-invalid' : '' }}" id="language" type="text" name="language" value="{{ old('language') }}" placeholder="Enter Candidate Language..">
                      @if ($errors->has('language'))
                        <span class="invalid-feedback help-block" role="alert">
                            <strong>{{ $errors->first('language') }}</strong>
                        </span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="col-md-6 mt-2">
                  <div class="card-body"  style="background: #fafafa; padding:1rem">
                    <div class="form-group">
                      <label class="font-weight-bold">Assign Service</label>
                      <select class="custom-select" name="category_id">
                        <option selected value="null">Select Service</option>
                        @foreach ($services as $service)
                          <option value="{{$service->id}}">{{$service->name}}</option>
                        @endforeach
                      </select>
                      @if ($errors->has('category_id'))
                        <span class="invalid-feedback help-block" role="alert" style="display:block">
                            <strong>{{ $errors->first('category_id') }}</strong>
                        </span>
                      @endif
                    </div>
                    <div class="form-group">
                      <label class="font-weight-bold">Set Level</label>
                      <select class="custom-select" name="level_id">
                        <option selected value="null">Select Level</option>
                        @foreach ($levels as $level)
                          <option value="{{$level->id}}">{{$level->level_name}}</option>
                        @endforeach
                      </select>
                      @if ($errors->has('level_id'))
                        <span class="invalid-feedback help-block" role="alert" style="display:block">
                            <strong>{{ $errors->first('level_id') }}</strong>
                        </span>
                      @endif
                    </div>
                    <div class="form-group">
                      <label class="font-weight-bold">Defalut Status</label>
                      <div class="form-check">
                        <input class="form-check-input" type="radio" name="status" value="1" checked>
                        <label class="form-check-label" for="inlineCheckbox2">Active</label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="radio" name="status" value="0">
                        <label class="form-check-label" for="inlineCheckbox2">Inactive</label>
                      </div>
                      @if ($errors->has('status'))
                        <span class="invalid-feedback help-block" role="alert">
                            <strong>{{ $errors->first('status') }}</strong>
                        </span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="col-md-6 mt-2">
                  <div class="card-body"  style="background: #fafafa; padding:1rem">
                    <div class="form-group">
                      <label class="font-weight-bold">Birth Date</label>
                      <input class="form-control{{ $errors->has('birthdate') ? ' is-invalid' : '' }}" id="birthdate" type="date" name="birthdate" value="{{ old('birthdate') }}" >
                      @if ($errors->has('birthdate'))
                        <span class="invalid-feedback help-block" role="alert">
                            <strong>{{ $errors->first('birthdate') }}</strong>
                        </span>
                      @endif
                    </div>
                    <div class="form-group">
                      <label class="font-weight-bold">Height</label>
                      <input class="form-control{{ $errors->has('height') ? ' is-invalid' : '' }}" id="height" type="text" name="height" value="{{ old('height') }}" placeholder="5'6">
                      @if ($errors->has('height'))
                        <span class="invalid-feedback help-block" role="alert">
                            <strong>{{ $errors->first('height') }}</strong>
                        </span>
                      @endif
                    </div>
                    <div class="form-group">
                      <label class="d-block font-weight-bold">Candidate Photo</label>
                      <input class="form-control-file{{$errors->has('photo') ? ' is-invalid' : '' }}" type="file" name="photo">
                      @if ($errors->has('photo'))
                        <span class="invalid-feedback help-block" role="alert">
                            <strong>{{ $errors->first('photo') }}</strong>
                        </span>
                      @endif
                    </div>
                  </div>
                </div>
              </div>
          </div>
          <div class="card-footer">
            <button class="btn  btn-primary" type="submit">
              <i class="fa fa-dot-circle-o"></i> Save Candidte</button>
            <button class="btn  btn-danger" type="reset">
              <i class="fa fa-ban"></i> Reset</button>
              </form>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row-->
  </div>
@endsection

resources/views/admin/orders/index.blade.php
@extends('layouts.back')

@section('content')
  <div class="animated fadeIn" >
    <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <i class="fa fa-align-justify"></i> All Order</div>
              <div class="card-body">
                <table class="table table-responsive-sm table-hover">
                  <thead>
                    <tr>
                      <th>Candidate</th>
                      <th>Customer</th>
                      <th>Book type</th>
                      <th>Duration</th>
                      <th>Amount</th>
                      <th>Phone</th>
                      <th>Location</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($orders as $order)
                      <tr>
                        <td>
                            <a title="Show Candidate" class="link" href="{{route('candidates.show', ['id' => $order->candidate['id']])}}">
                              {{$order->candidate['name']}}
                            </a>
                        </td>
                        <td>
                            <a title="Show Customer" class="link" href="{{route('customers.show', ['id' => $order->customer['id']])}}">
                              {{$order->customer['name']}}
                            </a>
                        </td>
                        <td>{{$order->book->name}}</td>
                        <td>{{$order->duration}}</td>
                        <td>{{$order->amount}}</td>
                        <td>{{$order->phone}}</td>
                        <td>{{$order->location}}</td>
                        <td>
                          <span class="badge badge-{{$order->status ? 'success': 'danger'}}">{{$order->status ? 'Active' : 'Inactive'}}</span>
                        </td>
                      </tr>
                    @empty

                    @endforelse
                  </tbody>
                </table>
                {{$orders->render()}}
              </div>
            </div>
        </div>
        <!-- /.col-->
    </div>
    <!-- /.row-->
  </div>

@endsection

resources/views/admin/orders/request.blade.php
@extends('layouts.back')

@section('content')
  <div class="animated fadeIn" >
    <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <i class="fa fa-align-justify"></i> All Order</div>
              <div class="card-body">
                <table class="table table-responsive-sm table-hover">
                  <thead>
                    <tr>
                      <th>Service</th>
                      <th>Customer</th>
                      <th>Book type</th>
                      <th>Duration</th>
                      <th>Amount</th>
                      <th>Phone</th>
                      <th>Location</th>
                      <th>Status</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($order_requests as $order_request)
                      <tr>
                        <td>
                            <a title="Show Service" class="link" href="{{route('services.show', ['id' => $order_request->service['id']])}}">
                              {{$order_request->service['name']}}
                            </a>
                        </td>
                        <td>
                            <a title="Show Customer" class="link" href="{{route('customers.show', ['id' => $order_request->customer['id']])}}">
                              {{$order_request->customer['name']}}
                            </a>
                        </td>
                        <td>{{$order_request->book->name}}</td>
                        <td>{{$order_request->duration}}</td>
                        <td>{{$order_request->amount}}</td>
                        <td>{{$order_request->phone}}</td>
                        <td>{{$order_request->location}}</td>
                        <td width='200'>
                          <span onclick="assignCandidate('{{$order_request->id }}')" style="cursor:pointer" class="badge badge-{{$order_request->status ==1? 'danger': 'success'}}">{{$order_request->status == 1? 'Not Assigned' : 'Assigned'}}</span>
                          {{-- <form id="assign-candidate-{{$order_request->id}}"  action="{{route('orders.assign')}}" method="post" style="display:none">
                              @csrf
                            <input type="hidden" name="order_id" value="{{$order_request->id}}" onchange="searchCandidate(this)">
                            <div class="input-group input-group-sm">
                                <input type="search" id="tag-candidate" name="candidate" value="" class="form-control" placeholder="" aria-label="" aria-describedby="basic-addon1">
                                <div class="input-group-append">
                                    <button class="btn btn-success" type="submit">Assign</button>
                                </div>
                            </div>
                          </form> --}}
                        </td>
                        <td>
                            @if ($order_request->status != 2)
                                <a title="Delete Request" onclick="requestDelete('{{route('orders.request.destroy', ['id' => $order_request->id])}}')" style="cursor:pointer">
                                  <i class="fa fa-trash"></i>
                                </a>
                            @endif
                        </td>
                      </tr>
                    @empty
                    @endforelse
                  </tbody>
                </table>
                {{$order_requests->render()}}
              </div>
            </div>
        </div>
        <!-- /.col-->
    </div>
    <!-- /.row-->
  </div>

  <div class="modal fade" id="assignCandidate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-success" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Find Candidate To Assign</h4>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close" onclick="$('#request_id').val('');$('#search').val('');$('#result').html('')">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
            <form id="assign" action="{{route('orders.assign')}}" method="post">
                @csrf
                <input type="hidden" id="request_id" name="request_id" value="">
                <input type="search" id="search" name="candidate" value="" autocomplete="off">
                <ul class="list-group" id="result" style="display:none">

                </ul>
        </div>
        <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal" onclick="$('#request_id').val('');$('#search').val('');$('#result').html('')">Close</button>
            <button class="btn btn-success" type="submit">Assign</button>
          </form>
        </div>
      </div>
      <!-- /.modal-content-->
    </div>
    <!-- /.modal-dialog-->
  </div>

  <div class="modal fade" id="requestDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-danger" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Are You Sure?</h4>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          <p>It will delete permanently</p>
        </div>
        <div class="modal-footer">
          <form id="delete" action="" method="post">
            @csrf
            @method('delete')
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
            <button class="btn btn-danger" type="submit">Delete</button>
          </form>
        </div>
      </div>
      <!-- /.modal-content-->
    </div>
    <!-- /.modal-dialog-->
  </div>
  @endsection

  @push('scripts')
  <script type="text/javascript">
    function requestDelete(url) {
      var form = document.getElementById('delete');
      form.action = url;

      $("#requestDelete").modal('show');
    }
  </script>
  @endpush


@push('scripts')
  <script type="text/javascript">
    function assignCandidate(id) {
      var form = document.getElementById('assign');
      // form.action = url;

      $('#request_id').val(id)


      $("#assignCandidate").modal('show');
    }

    $(function () {
        $(document).on('keyup', '#search', function () {
            $.ajax({
                method: "GET",
                url: "{{route('orders.candidate.find')}}",
                data: {
                    name: $(this).val(),
                    id: $('#request_id').val()
                },
                success: function (data) {
                    var list = '';
                    if (data.length) {
                        for (var i = 0; i < data.length; i++) {
                            list += `<li class="list-group-item" style="cursor:pointer" onclick="$('#search').val('${data[i]}'); $('#result').hide()">${data[i]}</li>`;
                        }
                        $('#result').show();
                        $('#result').html(list);
                    }
                }
            });
        })

    });

  </script>
@endpush